name: gputest

channels:
  - conda-forge
  - defaults

dependencies:
  - python 3.8.*
  - black
  - bokeh
  - cartopy
  - cdsapi 0.5.*
  - cudatoolkit 10.2.*
  - cudnn
  - dask
  - distributed 2021.*
  - ipywidgets
  - jupyterlab>=3.0.*
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - properscoring
  - pyaml
  - pylint
  - pip
  - s3cmd
  - scikit-learn
  - scipy
  - statsmodels
  - seaborn
  - tensorboard
  - torchvision=0.10.*=py38cuda102*
  - tqdm
  - pyro-ppl
  - pytorch=1.9.1=cuda102py38*
  - pytorch-lightning
  - timm=0.4.12
  - xarray
  - xskillscore
