#!/bin/bash
set -ex

docker image build \
    --build-arg username=ai4copernicus \
    --build-arg uid=1000 \
    --build-arg gid=100 \
    --tag "$DOCKER_REPO:latest" \
    --file Dockerfile \
    ../
